apiVersion: v2
name: helm-sample
icon: https://nabla.albandrieu.com/assets/nabla/nabla-4.png
home: https://albandrieu.com/
description: A Helm sample chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.4-prerelease+build
#version: 1.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

sources:
  - https://github.com/AlbanAndrieu/nabla-servers-bower-sample

maintainers:
  - name: aandrieu
    email: "alban.andrieu@free.fr"

#helm search repo bitnami
dependencies:
#- name: mysql
#  #bitnami/mariadb
#  version: 8.2.3
#  repository: https://charts.bitnami.com/bitnami/
#  alias: mysql-1
#  condition: mysql.enabled
#  tags:
#    - back-end
#    - mysql
#- name: configuration
#  repository: https://registry-tmp.albandrieu.com/chartrepo/nabla
##  repository: "@custom"
#  version: ^1.7.11
#- name: mongodb
#  version: 3.0.4
#  repository: https://kubernetes-charts.storage.googleapis.com/
#  condition: mongodb.enabled
